# Site settings
title: Viperswing
# the subpath baseurl must be to be publish & working in production under aquaboat.ch
# if you want to preview the website under username.github.io/aquaboat, you have to change baseurl to /aquaboat
baseurl: "/viperswing"
url: "http://www.viperswing.ch" # the base hostname & protocol for your site
email: ""

# Build settings
markdown: kramdown
exclude: [node_modules, gulp-config.json, Gulpfile.js, package.json, webpack-config.js]